version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-best_todo}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: best_todo.settings
      POSTGRES_DB: ${POSTGRES_DB:-best_todo}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      ALLOWED_HOSTS: "*"
      CORS_ALLOW_ALL_ORIGINS: "true"
    volumes:
      - .:/app
      - media:/app/media
      - static:/app/staticfiles
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - INLINE_RUNTIME_CHUNK=false
      - REACT_APP_API_BASE=http://localhost:8000/api
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"

volumes:
  pgdata:
  media:
  static:


